[package]
name = "lemonup-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lemonup"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crossterm.workspace = true
lemonup-core = { path = "../lemonup-core" }
ratatui.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
